# Generated by Django 3.0 on 2020-03-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_iin', models.CharField(max_length=255)),
                ('director_full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('movement_area', models.TextField()),
                ('email', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Status In Queued'), (1, 'Status Accepted'), (2, 'Status Declined')], default=0)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('officer_full_name', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationCar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_full_name', models.CharField(max_length=255)),
                ('car_identifier', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'application_car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicationSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone_number', models.CharField(max_length=255, verbose_name='Телефон')),
                ('reason', models.TextField(verbose_name='Причина')),
                ('output_time', models.TimeField(auto_now=True, verbose_name='Время выхода')),
                ('input_time', models.TimeField(verbose_name='Время возрата')),
                ('home_address', models.CharField(max_length=500, verbose_name='Адрес места жителства')),
                ('destination_address', models.CharField(max_length=500, verbose_name='Адрес пункта назначения')),
            ],
            options={
                'verbose_name': 'Анкета физ. лиц',
                'verbose_name_plural': 'Анкеты физ. лиц',
            },
        ),
    ]
