# Generated by Django 3.0 on 2020-03-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsingle',
            name='uid',
            field=models.CharField(max_length=255, null=True, verbose_name='UID'),
        ),
        migrations.AlterField(
            model_name='applicationsingle',
            name='home_address',
            field=models.CharField(max_length=500, verbose_name='Адрес места жительства'),
        ),
        migrations.AlterField(
            model_name='applicationsingle',
            name='input_time',
            field=models.TimeField(verbose_name='Время возврата'),
        ),
        migrations.AlterField(
            model_name='applicationsingle',
            name='output_time',
            field=models.TimeField(verbose_name='Время выхода'),
        ),
    ]
