version: '3'

volumes:
  mysql_data: {}
  media:

services:

  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app
      - media:./uploads
    environment:
      - SQL_DATABASE=transit_db
      - SQL_USER=root
      - SQL_PASSWORD=qwerty1234
      - SQL_HOST=db
      - SQL_PORT=3307
    command: /start

  db:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'transit_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'qwerty1234'
      MYSQL_ROOT_PASSWORD: 'qwerty1234'
    ports:
    - "3307:3306"
