#!/bin/sh
# Wait for database to get available

M_LOOPS="10"

#wait for mysql
i=0

while ! curl SQL_HOST:SQL_PORT >/dev/null 2>&1 < /dev/null; do
  i=`expr $i + 1`

  if [ $i -ge $M_LOOPS ]; then
    echo "$(date) - ${SQL_HOST}:${SQL_PORT} still not reachable, giving up"
    exit 1
  fi

  echo "$(date) - waiting for ${SQL_HOST}:${SQL_PORT}..."
  sleep 3
done

echo "$(date) - ${SQL_HOST}:${SQL_PORT} Reachable ! - Starting Daemon"
#start the daemon

python manage.py migrate
python manage.py runserver 0.0.0.0:8000
